In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score
import matplotlib.pyplot as plt
from scipy.stats import rankdata
import imblearn
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import RepeatedStratifiedKFold
from scipy.stats import randint

Using TensorFlow backend.


In [2]:
df = pd.read_csv('final_combined_dataset.csv')

In [3]:
df.head()

school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob  Fjob  ...  \
0       0    0   15        0        0        1     1     1     0     2  ...   
1       0    0   15        0        0        1     1     1     2     2  ...   
2       0    0   15        0        0        1     2     2     0     2  ...   
3       0    0   15        0        0        1     2     4     3     1  ...   
4       0    0   15        0        0        1     3     3     3     3  ...   

   famrel.y  freetime.y  goout.y  Dalc.y  Walc.y  health.y  absences.y  G1.y  \
0         3           1        2       1       1         1           4    13   
1         3           3        4       2       4         5           2    13   
2         4           3        1       1       1         2           8    14   
3         4           3        2       1       1         5           2    10   
4         4           2        1       2       3         3           2    13   

   G2.y  G3.y  
0    13    13  
1    11    11  
2    13    12  
3    11    10  
4    13    13  

[5 rows x 53 columns]

In [4]:
df = df.rename(columns = {'Unnamed: 0':'ID'})

In [5]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x',
       'G1.x', 'G2.x', 'G3.x', 'guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y', 'G1.y', 'G2.y', 'G3.y'],
      dtype='object')

In [6]:
xfeatures=['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x','G1.x','G3.x']

In [7]:
yfeatures = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet','guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y','G1.y','G3.y']

In [8]:
keepcol = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu',
       'Fedu', 'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x',
       'G1.x', 'G2.x', 'G3.x', 'guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y', 'G1.y', 'G2.y', 'G3.y']

In [9]:
fildf = df.loc[:,keepcol]

In [10]:
fildf_x = fildf.loc[:,xfeatures]

In [11]:
fildf_y = fildf.loc[:,yfeatures]

In [12]:
fildf_x.shape

(882, 32)

In [13]:
fildf_y.shape

(882, 32)

In [14]:
def convertmarks(mark):
    if mark<10:
        return 'F'
    elif mark==10 or mark==11:
        return 'D'
    elif mark==12 or mark==13:
        return 'C'
    elif mark==14 or mark==15:
        return'B'
    else:
        return 'A'

In [15]:
newlist=[]
for i in fildf_x['G1.x']:
    x = convertmarks(i)
    newlist.append(x)
fildf_x['New G1'] = newlist

In [16]:
newlist=[]
for i in fildf_y['G1.y']:
    x = convertmarks(i)
    newlist.append(x)
fildf_y['New G1'] = newlist

In [17]:
newlist=[]
for i in fildf_x['G3.x']:
    x = convertmarks(i)
    newlist.append(x)
fildf_x['New G3'] = newlist

In [18]:
newlist=[]
for i in fildf_y['G3.y']:
    x = convertmarks(i)
    newlist.append(x)
fildf_y['New G3'] = newlist

In [19]:
fildf_y['New G3']

0      C
1      D
2      C
3      D
4      C
      ..
877    C
878    B
879    C
880    C
881    C
Name: New G3, Length: 882, dtype: object

In [20]:
label_encoder = preprocessing.LabelEncoder()

In [21]:
fildf_x['New G1']= label_encoder.fit_transform(fildf_x['New G1'])
fildf_y['New G1']= label_encoder.fit_transform(fildf_y['New G1'])
fildf_x['New G3']= label_encoder.fit_transform(fildf_x['New G3'])
fildf_y['New G3']= label_encoder.fit_transform(fildf_y['New G3'])

In [22]:
fildf_y['New G3']

0      2
1      3
2      2
3      3
4      2
      ..
877    2
878    1
879    2
880    2
881    2
Name: New G3, Length: 882, dtype: int64

In [23]:
fildf_x = fildf_x.sample(frac=1,random_state=123)
fildf_y = fildf_y.sample(frac=1,random_state=123)

In [24]:
fildf_x = fildf_x.drop(['G1.x','G3.x'],axis=1)
fildf_y = fildf_y.drop(['G1.y','G3.y'],axis=1)

In [25]:
features_x_G3 = fildf_x.drop(['New G1','New G3'],axis=1)
features_x_G1 = fildf_x.drop(['New G1','New G3'],axis=1)
features_y_G3 = fildf_y.drop(['New G1','New G3'],axis=1)
features_y_G1 = fildf_y.drop(['New G1','New G3'],axis=1)

In [26]:
target_x_G3 = fildf_x['New G3']
target_x_G1 = fildf_x['New G1']
target_y_G3 = fildf_y['New G3']
target_y_G1 = fildf_y['New G1']

In [27]:
X_train_x_G1, X_test_x_G1, y_train_x_G1, y_test_x_G1 = train_test_split(features_x_G1, target_x_G1, test_size=0.25, random_state=0)
X_train_y_G1, X_test_y_G1, y_train_y_G1, y_test_y_G1 = train_test_split(features_y_G1, target_y_G1, test_size=0.25, random_state=0)

In [28]:
X_train_x_G3, X_test_x_G3, y_train_x_G3, y_test_x_G3 = train_test_split(features_x_G3, target_x_G3, test_size=0.25, random_state=0)
X_train_y_G3, X_test_y_G3, y_train_y_G3, y_test_y_G3 = train_test_split(features_y_G3, target_y_G3, test_size=0.25, random_state=0)

### SVM

In [31]:
param_grid_svc = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001],'kernel': ['linear','rbf', 'poly', 'sigmoid']}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [32]:
#grid_svc_x_G1 = GridSearchCV(SVC(),param_grid = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G1 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_svc_x_G1.best_estimator_)
y_pred_x_G1= grid_svc_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    2.2s
[Parallel(n_jobs=-1)]: Done 150 tasks      | elapsed:    7.2s


SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         0
           2       0.99      0.60      0.75       170
           3       0.17      0.46      0.24        13
           4       0.50      0.76      0.60        38

    accuracy                           0.62       221
   macro avg       0.33      0.36      0.32       221
weighted avg       0.86      0.62      0.69       221

[[  0   0  10   0   0]
 [  0   0  14   0   0]
 [  0   0 102   0   1]
 [  0   0  22   6   8]
 [  0   0  22   7  29]]
Kappa Score: 0.3522453679472417


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   41.5s finished
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
grid_svc_x_G3 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_svc_x_G3.best_estimator_)
y_pred_x_G3= grid_svc_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    1.7s


SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         1
           2       0.99      0.59      0.74       170
           3       0.05      1.00      0.09         1
           4       0.63      0.92      0.75        49

    accuracy                           0.67       221
   macro avg       0.33      0.50      0.32       221
weighted avg       0.90      0.67      0.74       221

[[  0   0  12   0   0]
 [  0   0  14   0   1]
 [  0   0 101   0   1]
 [  0   0  18   1   2]
 [  0   1  25   0  45]]
Kappa Score: 0.4156363896233831


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   10.0s finished
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
grid_svc_y_G1 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_svc_y_G1.best_estimator_)
y_pred_y_G1= grid_svc_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed:    2.0s
[Parallel(n_jobs=-1)]: Done 246 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  1.8min finished


SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.47      0.50      0.48        28
           2       0.88      0.72      0.80       138
           3       0.53      0.71      0.60        41
           4       0.54      0.58      0.56        12

    accuracy                           0.68       221
   macro avg       0.48      0.50      0.49       221
weighted avg       0.74      0.68      0.70       221

[[  0   5   5   0   0]
 [  2  14  13   1   0]
 [  0   6 100   7   0]
 [  0   2  19  29   5]
 [  0   1   1   4   7]]
Kappa Score: 0.47654790499065924


In [35]:
grid_svc_y_G3 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_svc_y_G3.best_estimator_)
y_pred_y_G3= grid_svc_y_G3.predict(X_test_y_G3)
print(metrics.classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.8s
[Parallel(n_jobs=-1)]: Done 182 tasks      | elapsed:   54.7s
[Parallel(n_jobs=-1)]: Done 285 out of 300 | elapsed:  1.0min remaining:    3.3s


SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.65      0.48      0.55        64
           2       0.74      0.62      0.68       112
           3       0.51      0.72      0.60        36
           4       0.40      0.44      0.42         9

    accuracy                           0.59       221
   macro avg       0.46      0.46      0.45       221
weighted avg       0.66      0.59      0.62       221

[[ 0  9  8  0  0]
 [ 0 31 17  0  0]
 [ 0 20 70  5  0]
 [ 0  4 16 26  5]
 [ 0  0  1  5  4]]
Kappa Score: 0.400957744782098


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  1.1min finished
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Gradient Boosting

In [36]:
gbc = GradientBoostingClassifier()
parameters_gbc = {
    "n_estimators":[5,50,250,500],
    "max_depth":[1,3,5,7,9],
    "learning_rate":[0.01,0.1,1,10,100]
}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [37]:
grid_gbc_x_G1 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_gbc_x_G1.best_estimator_)
y_pred_x_G1= grid_gbc_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    2.5s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   39.0s


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=5,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         0
           2       0.99      0.60      0.75       170
           3       0.33      0.67      0.44        18
           4       0.53      0.94 

[Parallel(n_jobs=-1)]: Done 285 out of 300 | elapsed:   54.3s remaining:    2.9s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   54.3s finished
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
grid_gbc_x_G3 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_gbc_x_G3.best_estimator_)
y_pred_x_G3= grid_gbc_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed:    1.9s
/opt/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
[Parallel(n_jobs=-1)]: Done 242 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  3.1min finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=7,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.17      0.25      0.20         8
           1       0.07      0.11      0.08         9
           2       0.88      0.64      0.74       141
           3       0.10      0.29      0.14         7
           4       0.68      0.8

In [39]:
grid_gbc_y_G1 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_gbc_y_G1.best_estimator_)
y_pred_y_G1= grid_gbc_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.9s
/opt/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  3.7min finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=1,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=250,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.27      0.67      0.38        12
           2       0.92      0.62      0.74       167
           3       0.42      0.68      0.52        34
           4       0.31      0.5

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [40]:
grid_gbc_y_G3 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_gbc_y_G3.best_estimator_)
y_pred_y_G3= grid_gbc_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  1.9min finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=50,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.12      0.50      0.19         4
           1       0.29      0.45      0.35        31
           2       0.82      0.51      0.63       153
           3       0.29      0.58      0.39        26
           4       0.40      0.57

### Logistic Regression

In [41]:
lr = LogisticRegression(max_iter=1000)
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [10, 1.0, 0.1, 0.01]
grid = dict(solver=solvers,penalty=penalty,C=c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [42]:
grid_search_lr_x_G1 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_lr_x_G1.best_estimator_)
y_pred_x_G1= grid_search_lr_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         0
           2       0.99      0.60      0.75       170
           3       0.25      0.64      0.36        14
           4       0.55      0.86      0.67        37

    accuracy                           0.65       221
   macro avg       0.36      0.42      0.36       221
weighted avg       0.87      0.65      0.71       221

[[  0   0  10   0   0]
 [  0   0  14   0   0]
 [  0   0 102   1   0]
 [  0   0  22   9   5]
 [  0   0  22   4  32]]
Kappa Score: 0.39897493113908156


/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [43]:
grid_search_lr_x_G3 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_lr_x_G3.best_estimator_)
y_pred_x_G3= grid_search_lr_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         0
           2       0.99      0.59      0.74       170
           3       0.00      0.00      0.00         0
           4       0.65      0.90      0.75        51

    accuracy                           0.67       221
   macro avg       0.33      0.30      0.30       221
weighted avg       0.91      0.67      0.75       221

[[  0   0  12   0   0]
 [  0   0  14   0   1]
 [  0   0 101   0   1]
 [  0   0  18   0   3]
 [  0   0  25   0  46]]
Kappa Score: 0.4134146341463415


/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [44]:
grid_search_lr_y_G1 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_lr_y_G1.best_estimator_)
y_pred_y_G1= grid_search_lr_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.30      0.60      0.40        15
           2       0.87      0.64      0.74       152
           3       0.49      0.66      0.56        41
           4       0.62      0.62      0.62        13

    accuracy                           0.64       221
   macro avg       0.45      0.50      0.46       221
weighted avg       0.74      0.64      0.68       221

[[ 0  2  8  0  0]
 [ 0  9 20  0  1]
 [ 0  4 98 11  0]
 [ 0  0 24 27  4]
 [ 0  0  2  3  8]]
Kappa Score: 0.3935952207286999


/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [45]:
grid_search_lr_y_G3 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_lr_y_G3.best_estimator_)
y_pred_y_G3= grid_search_lr_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.54      0.48      0.51        54
           2       0.76      0.62      0.68       117
           3       0.51      0.68      0.58        38
           4       0.40      0.40      0.40        10

    accuracy                           0.58       221
   macro avg       0.44      0.44      0.43       221
weighted avg       0.64      0.58      0.60       221

[[ 0  8  8  1  0]
 [ 2 26 20  0  0]
 [ 0 17 72  6  0]
 [ 0  3 16 26  6]
 [ 0  0  1  5  4]]
Kappa Score: 0.3783497671042283


### Random Forest

In [46]:
# define models and parameters
rf = RandomForestClassifier()
n_estimators = [10, 100, 1000]
max_features = ['sqrt', 'log2']
# define grid search
grid = dict(n_estimators=n_estimators,max_features=max_features)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [47]:
grid_search_rf_x_G1 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_rf_x_G1.best_estimator_)
y_pred_x_G1= grid_search_rf_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.10      1.00      0.18         1
           1       0.07      1.00      0.13         1
           2       0.99      0.61      0.76       167
           3       0.36      0.72      0.48        18
           4       0.55      0.94      0.70        34

    accuracy                           0.67       221
   macro avg       0.41      0.85      0.45       221
weighted avg      

In [48]:
grid_search_rf_x_G3 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_rf_x_G3.best_estimator_)
y_pred_x_G3= grid_search_rf_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.17      1.00      0.29         2
           1       0.00      0.00      0.00         0
           2       0.99      0.61      0.75       166
           3       0.00      0.00      0.00         0
           4       0.68      0.91      0.77        53

    accuracy                           0.68       221
   macro avg       0.37      0.50      0.36       221
weighted avg      

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [49]:
grid_search_rf_y_G1 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_rf_y_G1.best_estimator_)
y_pred_y_G1= grid_search_rf_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.10      1.00      0.18         1
           1       0.10      0.60      0.17         5
           2       0.95      0.58      0.72       185
           3       0.31      0.63      0.41        27
           4       0.15      0.67      0.25         3

    accuracy                           0.59       221
   macro avg       0.32      0.69      0.35       221
weighted avg      

In [50]:
grid_search_rf_y_G3 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_rf_y_G3.best_estimator_)
y_pred_y_G3= grid_search_rf_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.19      0.50      0.27        18
           2       0.93      0.48      0.63       183
           3       0.24      0.63      0.34        19
           4       0.10      1.00      0.18         1

    accuracy                           0.50       221
   macro avg       0.29      0.52      0.29       221
weighted avg      

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Decision Tree

In [51]:
dct = DecisionTreeClassifier()
param_dist = {"max_depth": [1,2,3,4,5],
              "max_features": ['auto', 'sqrt', 'log2'],
              "min_samples_leaf": [1,2,3,4,5],
              "min_samples_split" : [1,2,3,4,5],
              "criterion": ["gini", "entropy"]}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [52]:
grid_search_dct_x_G1 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_dct_x_G1.best_estimator_)
y_pred_x_G1= grid_search_dct_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=5, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         0
           2       0.91      0.57      0.70       164
           3       0.31      0.69      0.42        16
           4       0.47      0.68      0.55        40

    accuracy                           0.60       221
   macro avg       0.34      0.39      0.34       221
weighted avg       0.78      0.60      0.65       221

[[ 0  0  8  0  2]
 [ 0  0 14  0  0]
 [ 0  0 94  1  8]
 [ 0  0 22 11  3]
 [ 1  0 26

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [53]:
grid_search_dct_x_G3 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_dct_x_G3.best_estimator_)
y_pred_x_G3= grid_search_dct_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=3, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         0
           2       0.92      0.46      0.62       203
           3       0.00      0.00      0.00         0
           4       0.07      0.28      0.11        18

    accuracy                           0.45       221
   macro avg       0.20      0.15      0.15       221
weighted avg       0.85      0.45      0.58       221

[[ 0  0 12  0  0]
 [ 0  0 12  0  3]
 [ 0  0 94  0  8]
 [ 0  0 19  0  2]
 [ 0  0 66

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [54]:
grid_search_dct_y_G1 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_dct_y_G1.best_estimator_)
y_pred_y_G1= grid_search_dct_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         1
           2       0.89      0.55      0.68       185
           3       0.22      0.43      0.29        28
           4       0.08      0.14      0.10         7

    accuracy                           0.52       221
   macro avg       0.24      0.22      0.21       221
weighted avg       0.78      0.52      0.61       221

[[  0   0   7   3   0]
 [  0   0  29   1   0]
 [  0   0 101   9   3]
 [  0   0  40

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [55]:
grid_search_dct_y_G3 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_dct_y_G3.best_estimator_)
y_pred_y_G3= grid_search_rf_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=2, max_features='log2', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.19      0.50      0.27        18
           2       0.93      0.48      0.63       183
           3       0.24      0.63      0.34        19
           4       0.10      1.00      0.18         1

    accuracy                           0.50       221
   macro avg       0.29      0.52      0.29       221
weighted avg       0.80      0.50      0.58       221

[[ 0  3 14  0  0]
 [ 0  9 39  0  0]
 [ 0  6 88  1  0]
 [ 0  0 39 12  0]
 [ 0  0  3  6

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Gaussian Naive Bayesian

In [56]:
clf = GaussianNB()

In [57]:
clf.fit(X_train_x_G1,y_train_x_G1)
y_pred_x_G1= clf.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))
probagnbG1x = clf.predict_proba(X_test_x_G1)

              precision    recall  f1-score   support

           0       0.90      0.07      0.13       126
           1       0.00      0.00      0.00         0
           2       0.19      0.61      0.29        33
           3       0.31      0.58      0.40        19
           4       0.52      0.70      0.59        43

    accuracy                           0.32       221
   macro avg       0.38      0.39      0.28       221
weighted avg       0.67      0.32      0.27       221

Kappa Score: 0.1861525704809287


/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [58]:
clf.fit(X_train_x_G3,y_train_x_G3)
y_pred_x_G3= clf.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))
probagnbG3x = clf.predict_proba(X_test_x_G3)

              precision    recall  f1-score   support

           0       0.08      0.04      0.05        27
           1       0.80      0.12      0.21       102
           2       0.19      0.61      0.29        31
           3       0.10      0.33      0.15         6
           4       0.61      0.78      0.68        55

    accuracy                           0.35       221
   macro avg       0.35      0.38      0.27       221
weighted avg       0.56      0.35      0.31       221

Kappa Score: 0.20028144946474324


In [59]:
clf.fit(X_train_y_G1,y_train_y_G1)
y_pred_y_G1 = clf.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))
probagnbG1y = clf.predict_proba(X_test_y_G1)

              precision    recall  f1-score   support

           0       0.70      0.05      0.09       150
           1       0.10      0.12      0.11        24
           2       0.04      0.44      0.07         9
           3       0.24      0.68      0.35        19
           4       0.62      0.42      0.50        19

    accuracy                           0.16       221
   macro avg       0.34      0.34      0.22       221
weighted avg       0.56      0.16      0.15       221

Kappa Score: 0.07235060480231092


In [60]:
clf.fit(X_train_y_G3,y_train_y_G3)
y_pred_y_G3 = clf.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))
probagnbG3y = clf.predict_proba(X_test_y_G3)

              precision    recall  f1-score   support

           0       0.29      0.11      0.16        47
           1       0.75      0.30      0.43       120
           2       0.14      0.57      0.22        23
           3       0.25      0.68      0.37        19
           4       0.70      0.58      0.64        12

    accuracy                           0.33       221
   macro avg       0.43      0.45      0.36       221
weighted avg       0.54      0.33      0.36       221

Kappa Score: 0.16717083675143563
