In [50]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score
import matplotlib.pyplot as plt
from scipy.stats import rankdata
import imblearn
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import RepeatedStratifiedKFold
from scipy.stats import randint

In [2]:
df = pd.read_csv('final_combined_dataset.csv')

In [3]:
df.head()

school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob  Fjob  ...  \
0       0    0   15        0        0        1     1     1     0     2  ...   
1       0    0   15        0        0        1     1     1     2     2  ...   
2       0    0   15        0        0        1     2     2     0     2  ...   
3       0    0   15        0        0        1     2     4     3     1  ...   
4       0    0   15        0        0        1     3     3     3     3  ...   

   famrel.y  freetime.y  goout.y  Dalc.y  Walc.y  health.y  absences.y  G1.y  \
0         3           1        2       1       1         1           4    13   
1         3           3        4       2       4         5           2    13   
2         4           3        1       1       1         2           8    14   
3         4           3        2       1       1         5           2    10   
4         4           2        1       2       3         3           2    13   

   G2.y  G3.y  
0    13    13  
1    11    11  
2    13    12  
3    11    10  
4    13    13  

[5 rows x 53 columns]

In [4]:
df = df.rename(columns = {'Unnamed: 0':'ID'})

In [5]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x',
       'G1.x', 'G2.x', 'G3.x', 'guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y', 'G1.y', 'G2.y', 'G3.y'],
      dtype='object')

In [6]:
xfeatures=['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x','G1.x','G3.x']

In [7]:
yfeatures = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet','guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y','G1.y','G3.y']

In [8]:
keepcol = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu',
       'Fedu', 'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x',
       'G1.x', 'G2.x', 'G3.x', 'guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y', 'G1.y', 'G2.y', 'G3.y']

In [9]:
fildf = df.loc[:,keepcol]

In [10]:
fildf_x = fildf.loc[:,xfeatures]

In [11]:
fildf_y = fildf.loc[:,yfeatures]

In [12]:
fildf_x.shape

(882, 32)

In [13]:
fildf_y.shape

(882, 32)

In [14]:
def convertmarks(mark):
    if mark<10:
        return 'B'
    else:
        return 'A'

In [15]:
newlist=[]
for i in fildf_x['G1.x']:
    x = convertmarks(i)
    newlist.append(x)
fildf_x['New G1'] = newlist

In [16]:
newlist=[]
for i in fildf_y['G1.y']:
    x = convertmarks(i)
    newlist.append(x)
fildf_y['New G1'] = newlist

In [17]:
newlist=[]
for i in fildf_x['G3.x']:
    x = convertmarks(i)
    newlist.append(x)
fildf_x['New G3'] = newlist

In [18]:
newlist=[]
for i in fildf_y['G3.y']:
    x = convertmarks(i)
    newlist.append(x)
fildf_y['New G3'] = newlist

In [19]:
fildf_y['New G3']

0      A
1      A
2      A
3      A
4      A
      ..
877    A
878    A
879    A
880    A
881    A
Name: New G3, Length: 882, dtype: object

In [20]:
label_encoder = preprocessing.LabelEncoder()

In [21]:
fildf_x['New G1']= label_encoder.fit_transform(fildf_x['New G1'])
fildf_y['New G1']= label_encoder.fit_transform(fildf_y['New G1'])
fildf_x['New G3']= label_encoder.fit_transform(fildf_x['New G3'])
fildf_y['New G3']= label_encoder.fit_transform(fildf_y['New G3'])

In [22]:
fildf_y['New G3']

0      0
1      0
2      0
3      0
4      0
      ..
877    0
878    0
879    0
880    0
881    0
Name: New G3, Length: 882, dtype: int64

In [23]:
fildf_x = fildf_x.sample(frac=1,random_state=123)
fildf_y = fildf_y.sample(frac=1,random_state=123)

In [24]:
fildf_x = fildf_x.drop(['G1.x','G3.x'],axis=1)
fildf_y = fildf_y.drop(['G1.y','G3.y'],axis=1)

In [25]:
features_x_G3 = fildf_x.drop(['New G1','New G3'],axis=1)
features_x_G1 = fildf_x.drop(['New G1','New G3'],axis=1)
features_y_G3 = fildf_y.drop(['New G1','New G3'],axis=1)
features_y_G1 = fildf_y.drop(['New G1','New G3'],axis=1)

In [26]:
target_x_G3 = fildf_x['New G3']
target_x_G1 = fildf_x['New G1']
target_y_G3 = fildf_y['New G3']
target_y_G1 = fildf_y['New G1']

In [27]:
X_train_x_G1, X_test_x_G1, y_train_x_G1, y_test_x_G1 = train_test_split(features_x_G1, target_x_G1, test_size=0.25, random_state=0)
X_train_y_G1, X_test_y_G1, y_train_y_G1, y_test_y_G1 = train_test_split(features_y_G1, target_y_G1, test_size=0.25, random_state=0)

In [28]:
X_train_x_G3, X_test_x_G3, y_train_x_G3, y_test_x_G3 = train_test_split(features_x_G3, target_x_G3, test_size=0.25, random_state=0)
X_train_y_G3, X_test_y_G3, y_train_y_G3, y_test_y_G3 = train_test_split(features_y_G3, target_y_G3, test_size=0.25, random_state=0)

### SVM

In [29]:
param_grid_svc = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001],'kernel': ['linear','rbf', 'poly', 'sigmoid']}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [30]:
grid_svc_x_G1 = GridSearchCV(SVC(),param_grid = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_svc_x_G1.best_estimator_)
y_pred_x_G1= grid_svc_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

Fitting 30 folds for each of 64 candidates, totalling 1920 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    1.6s
[Parallel(n_jobs=-1)]: Done 602 tasks      | elapsed:    6.4s
[Parallel(n_jobs=-1)]: Done 1565 tasks      | elapsed:   24.1s


SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.99      0.87      0.92       186
           1       0.57      0.94      0.71        35

    accuracy                           0.88       221
   macro avg       0.78      0.90      0.82       221
weighted avg       0.92      0.88      0.89       221

[[161   2]
 [ 25  33]]
Kappa Score: 0.6382101497605044


[Parallel(n_jobs=-1)]: Done 1920 out of 1920 | elapsed:   37.7s finished


In [31]:
grid_svc_x_G3 = GridSearchCV(SVC(),param_grid = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_svc_x_G3.best_estimator_)
y_pred_x_G3= grid_svc_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

Fitting 30 folds for each of 64 candidates, totalling 1920 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done 160 tasks      | elapsed:    1.3s
[Parallel(n_jobs=-1)]: Done 1112 tasks      | elapsed:   15.1s
[Parallel(n_jobs=-1)]: Done 1603 tasks      | elapsed:   32.7s


SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.97      0.85      0.91       170
           1       0.65      0.90      0.75        51

    accuracy                           0.86       221
   macro avg       0.81      0.88      0.83       221
weighted avg       0.89      0.86      0.87       221

[[145   5]
 [ 25  46]]
Kappa Score: 0.6637931034482758


[Parallel(n_jobs=-1)]: Done 1905 out of 1920 | elapsed:   46.8s remaining:    0.4s
[Parallel(n_jobs=-1)]: Done 1920 out of 1920 | elapsed:   46.8s finished


In [32]:
grid_svc_y_G1 = GridSearchCV(SVC(),param_grid = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_svc_y_G1.best_estimator_)
y_pred_y_G1= grid_svc_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

Fitting 30 folds for each of 64 candidates, totalling 1920 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done 214 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done 1705 tasks      | elapsed:   42.2s


SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       213
           1       0.54      0.88      0.67         8

    accuracy                           0.97       221
   macro avg       0.77      0.92      0.83       221
weighted avg       0.98      0.97      0.97       221

[[207   1]
 [  6   7]]
Kappa Score: 0.6510263929618768


[Parallel(n_jobs=-1)]: Done 1920 out of 1920 | elapsed:  1.1min finished


In [33]:
grid_svc_y_G3 = GridSearchCV(SVC(),param_grid = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_svc_y_G3.best_estimator_)
y_pred_y_G3= grid_svc_y_G3.predict(X_test_y_G3)
print(metrics.classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 64 candidates, totalling 1920 fits


[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:    1.0s
[Parallel(n_jobs=-1)]: Done 1820 tasks      | elapsed:   26.2s
[Parallel(n_jobs=-1)]: Done 1905 out of 1920 | elapsed:   28.0s remaining:    0.2s


SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       217
           1       0.40      1.00      0.57         4

    accuracy                           0.97       221
   macro avg       0.70      0.99      0.78       221
weighted avg       0.99      0.97      0.98       221

[[211   0]
 [  6   4]]
Kappa Score: 0.5600530856005309


[Parallel(n_jobs=-1)]: Done 1920 out of 1920 | elapsed:   28.6s finished


### Gradient Boosting

In [71]:
gbc = GradientBoostingClassifier()
parameters_gbc = {
    "n_estimators":[5,50,250,500],
    "max_depth":[1,3,5,7,9],
    "learning_rate":[0.01,0.1,1,10,100]
}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [72]:
grid_gbc_x_G1 = GridSearchCV(gbc,param_grid = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_gbc_x_G1.best_estimator_)
y_pred_x_G1= grid_gbc_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

Fitting 30 folds for each of 100 candidates, totalling 3000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    2.5s
[Parallel(n_jobs=-1)]: Done 322 tasks      | elapsed:   15.1s
[Parallel(n_jobs=-1)]: Done 555 tasks      | elapsed:   48.8s
[Parallel(n_jobs=-1)]: Done 1032 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done 1609 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-1)]: Done 2304 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done 3000 out of 3000 | elapsed:  3.8min finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.01, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=250,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.99      0.87      0.92       186
           1       0.57      0.94      0.71        35

    accuracy                           0.88       221
   macro avg       0.78      0.90      0.82       221
weighted avg       0.92      0

In [36]:
grid_gbc_x_G3 = GridSearchCV(gbc,param_grid = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_gbc_x_G3.best_estimator_)
y_pred_x_G3= grid_gbc_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

Fitting 30 folds for each of 100 candidates, totalling 3000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done 214 tasks      | elapsed:    8.3s
/opt/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
[Parallel(n_jobs=-1)]: Done 714 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 1053 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done 1517 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-1)]: Done 2150 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-1)]: Done 2973 tasks      | elapsed:  3.5min
[Parallel(n_jobs=-1)]: Done 3000 out of 3000 | elapsed:  3.7min finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.01, loss='deviance', max_depth=1,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.97      0.85      0.91       170
           1       0.65      0.90      0.75        51

    accuracy                           0.86       221
   macro avg       0.81      0.88      0.83       221
weighted avg       0.89      0

In [37]:
grid_gbc_y_G1 = GridSearchCV(gbc,param_grid = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_gbc_y_G1.best_estimator_)
y_pred_y_G1= grid_gbc_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

Fitting 30 folds for each of 100 candidates, totalling 3000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done 268 tasks      | elapsed:   10.1s
/opt/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
[Parallel(n_jobs=-1)]: Done 892 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 1209 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 1976 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-1)]: Done 2433 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-1)]: Done 2985 out of 3000 | elapsed:  2.7min remaining:    0.8s


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=1,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=250,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       215
           1       0.38      0.83      0.53         6

    accuracy                           0.96       221
   macro avg       0.69      0.90      0.75       221
weighted avg       0.98      0.

[Parallel(n_jobs=-1)]: Done 3000 out of 3000 | elapsed:  2.8min finished


In [38]:
grid_gbc_y_G3 = GridSearchCV(gbc,param_grid = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_gbc_y_G3.best_estimator_)
y_pred_y_G3= grid_gbc_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 100 candidates, totalling 3000 fits


[Parallel(n_jobs=-1)]: Done 160 tasks      | elapsed:    4.1s
[Parallel(n_jobs=-1)]: Done 618 tasks      | elapsed:   47.5s
[Parallel(n_jobs=-1)]: Done 928 tasks      | elapsed:   59.6s
[Parallel(n_jobs=-1)]: Done 1774 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 2562 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-1)]: Done 3000 out of 3000 | elapsed:  2.5min finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=250,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       213
           1       0.40      0.50      0.44         8

    accuracy                           0.95       221
   macro avg       0.69      0.74      0.71       221
weighted avg       0.96      0.

### Logistic Regression

In [39]:
lr = LogisticRegression(max_iter=10000)
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01]
grid = dict(solver=solvers,penalty=penalty,C=c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [40]:
grid_search_lr_x_G1 = GridSearchCV(estimator=lr, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_lr_x_G1.best_estimator_)
y_pred_x_G1= grid_search_lr_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.98      0.84      0.91       190
           1       0.48      0.90      0.63        31

    accuracy                           0.85       221
   macro avg       0.73      0.87      0.77       221
weighted avg       0.91      0.85      0.87       221

[[160   3]
 [ 30  28]]
Kappa Score: 0.5462576992471847


In [41]:
grid_search_lr_x_G3 = GridSearchCV(estimator=lr, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_lr_x_G3.best_estimator_)
y_pred_x_G3= grid_search_lr_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.97      0.82      0.89       178
           1       0.55      0.91      0.68        43

    accuracy                           0.84       221
   macro avg       0.76      0.86      0.79       221
weighted avg       0.89      0.84      0.85       221

[[146   4]
 [ 32  39]]
Kappa Score: 0.5831936295054485


In [42]:
grid_search_lr_y_G1 = GridSearchCV(estimator=lr, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_lr_y_G1.best_estimator_)
y_pred_y_G1= grid_search_lr_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.98      0.97      0.97       211
           1       0.46      0.60      0.52        10

    accuracy                           0.95       221
   macro avg       0.72      0.78      0.75       221
weighted avg       0.96      0.95      0.95       221

[[204   4]
 [  7   6]]
Kappa Score: 0.49595687331536387


In [43]:
grid_search_lr_y_G3 = GridSearchCV(estimator=lr, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_lr_y_G3.best_estimator_)
y_pred_y_G3= grid_search_lr_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       214
           1       0.40      0.57      0.47         7

    accuracy                           0.96       221
   macro avg       0.69      0.77      0.72       221
weighted avg       0.97      0.96      0.96       221

[[208   3]
 [  6   4]]
Kappa Score: 0.4500967652750898


### Random Forest

In [44]:
# define models and parameters
rf = RandomForestClassifier()
n_estimators = [10, 100, 1000]
max_features = ['sqrt', 'log2']
# define grid search
grid = dict(n_estimators=n_estimators,max_features=max_features)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [45]:
grid_search_rf_x_G1 = GridSearchCV(estimator=rf, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_rf_x_G1.best_estimator_)
y_pred_x_G1= grid_search_rf_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.99      0.87      0.93       187
           1       0.57      0.97      0.72        34

    accuracy                           0.88       221
   macro avg       0.78      0.92      0.82       221
weighted avg       0.93      0.88      0.89       221

[[162   1]
 [ 25  33]]
Kappa Score: 0.6493775933609959


In [46]:
grid_search_rf_x_G3 = GridSearchCV(estimator=rf, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_rf_x_G3.best_estimator_)
y_pred_x_G3= grid_search_rf_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.98      0.85      0.91       173
           1       0.63      0.94      0.76        48

    accuracy                           0.87       221
   macro avg       0.81      0.89      0.83       221
weighted avg       0.90      0.87      0.88       221

[[147   3]
 [ 26  45]]
Kappa Score: 0.671046553405533


In [47]:
grid_search_rf_y_G1 = GridSearchCV(estimator=rf, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_rf_y_G1.best_estimator_)
y_pred_y_G1= grid_search_rf_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

/opt/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       220
           1       0.08      1.00      0.14         1

    accuracy                           0.95       221
   macro avg       0.54      0.97      0.56       221
weighted avg       1.00      0.95      0.97       221

[[208   0]
 [ 12   1]]
Kappa Score: 0.13559322033898302


In [48]:
grid_search_rf_y_G3 = GridSearchCV(estimator=rf, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_rf_y_G3.best_estimator_)
y_pred_y_G3= grid_search_rf_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       220
           1       0.10      1.00      0.18         1

    accuracy                           0.96       221
   macro avg       0.55      0.98      0.58       221
weighted avg       1.00      0.96      0.98       221

[[211   0]
 [  9   1]]
Kappa Score: 0.17503110742430528


### Decision Tree

In [68]:
dct = DecisionTreeClassifier()
param_dist = {"max_depth": [1,2,3,4,5],
              "max_features": ['auto', 'sqrt', 'log2'],
              "min_samples_leaf": [1,2,3,4,5],
              "min_samples_split" : [1,2,3,4,5],
              "criterion": ["gini", "entropy"]}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [69]:
grid_search_dct_x_G1 = GridSearchCV(estimator=dct, param_grid=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_dct_x_G1.best_estimator_)
y_pred_x_G1= grid_search_dct_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=5, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.97      0.82      0.89       192
           1       0.41      0.83      0.55        29

    accuracy                           0.82       221
   macro avg       0.69      0.83      0.72       221
weighted avg       0.90      0.82      0.85       221

[[158   5]
 [ 34  24]]
Kappa Score: 0.456660152556263


In [70]:
grid_search_dct_x_G3 = GridSearchCV(estimator=dct, param_grid=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_dct_x_G3.best_estimator_)
y_pred_x_G3= grid_search_dct_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.96      0.76      0.85       189
           1       0.37      0.81      0.50        32

    accuracy                           0.77       221
   macro avg       0.66      0.79      0.68       221
weighted avg       0.87      0.77      0.80       221

[[144   6]
 [ 45  26]]
Kappa Score: 0.3813601185575498


In [59]:
grid_search_dct_y_G1 = GridSearchCV(estimator=dct, param_grid=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_dct_y_G1.best_estimator_)
y_pred_y_G1= grid_search_dct_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=2, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.98      0.95      0.97       214
           1       0.23      0.43      0.30         7

    accuracy                           0.94       221
   macro avg       0.61      0.69      0.63       221
weighted avg       0.96      0.94      0.95       221

[[204   4]
 [ 10   3]]
Kappa Score: 0.26993865030674846


In [61]:
grid_search_dct_y_G3 = GridSearchCV(estimator=dct, param_grid=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_dct_y_G3.best_estimator_)
y_pred_y_G3= grid_search_rf_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       220
           1       0.10      1.00      0.18         1

    accuracy                           0.96       221
   macro avg       0.55      0.98      0.58       221
weighted avg       1.00      0.96      0.98       221

[[211   0]
 [  9   1]]
Kappa Score: 0.17503110742430528


### Gaussian Naive Bayesian

In [63]:
clf = GaussianNB()

In [64]:
clf.fit(X_train_x_G1,y_train_x_G1)
y_pred_x_G1= clf.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))
probagnbG1x = clf.predict_proba(X_test_x_G1)

              precision    recall  f1-score   support

           0       0.93      0.85      0.89       178
           1       0.55      0.74      0.63        43

    accuracy                           0.83       221
   macro avg       0.74      0.80      0.76       221
weighted avg       0.86      0.83      0.84       221

Kappa Score: 0.5282409277101483


In [65]:
clf.fit(X_train_x_G3,y_train_x_G3)
y_pred_x_G3= clf.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))
probagnbG3x = clf.predict_proba(X_test_x_G3)

              precision    recall  f1-score   support

           0       0.91      0.83      0.87       164
           1       0.61      0.75      0.67        57

    accuracy                           0.81       221
   macro avg       0.76      0.79      0.77       221
weighted avg       0.83      0.81      0.82       221

Kappa Score: 0.5403585223333663


In [66]:
clf.fit(X_train_y_G1,y_train_y_G1)
y_pred_y_G1 = clf.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))
probagnbG1y = clf.predict_proba(X_test_y_G1)

              precision    recall  f1-score   support

           0       0.91      0.98      0.95       193
           1       0.77      0.36      0.49        28

    accuracy                           0.90       221
   macro avg       0.84      0.67      0.72       221
weighted avg       0.90      0.90      0.89       221

Kappa Score: 0.4430577223088923


In [67]:
clf.fit(X_train_y_G3,y_train_y_G3)
y_pred_y_G3 = clf.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))
probagnbG3y = clf.predict_proba(X_test_y_G3)

              precision    recall  f1-score   support

           0       0.93      0.99      0.96       199
           1       0.80      0.36      0.50        22

    accuracy                           0.93       221
   macro avg       0.87      0.68      0.73       221
weighted avg       0.92      0.93      0.92       221

Kappa Score: 0.46682750301568154
