In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score
import matplotlib.pyplot as plt
from scipy.stats import rankdata
import imblearn
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import RepeatedStratifiedKFold
from scipy.stats import randint

Using TensorFlow backend.


In [2]:
df = pd.read_csv('final_combined_dataset.csv')

In [3]:
df.head()

school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob  Fjob  ...  \
0       0    0   15        0        0        1     1     1     0     2  ...   
1       0    0   15        0        0        1     1     1     2     2  ...   
2       0    0   15        0        0        1     2     2     0     2  ...   
3       0    0   15        0        0        1     2     4     3     1  ...   
4       0    0   15        0        0        1     3     3     3     3  ...   

   famrel.y  freetime.y  goout.y  Dalc.y  Walc.y  health.y  absences.y  G1.y  \
0         3           1        2       1       1         1           4    13   
1         3           3        4       2       4         5           2    13   
2         4           3        1       1       1         2           8    14   
3         4           3        2       1       1         5           2    10   
4         4           2        1       2       3         3           2    13   

   G2.y  G3.y  
0    13    13  
1    11    11  
2    13    12  
3    11    10  
4    13    13  

[5 rows x 53 columns]

In [4]:
df = df.rename(columns = {'Unnamed: 0':'ID'})

In [5]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x',
       'G1.x', 'G2.x', 'G3.x', 'guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y', 'G1.y', 'G2.y', 'G3.y'],
      dtype='object')

In [6]:
xfeatures=['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x','G1.x','G3.x']

In [7]:
yfeatures = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet','guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y','G1.y','G3.y']

In [8]:
keepcol = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu',
       'Fedu', 'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x',
       'G1.x', 'G2.x', 'G3.x', 'guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y', 'G1.y', 'G2.y', 'G3.y']

In [9]:
fildf = df.loc[:,keepcol]

In [10]:
fildf_x = fildf.loc[:,xfeatures]

In [11]:
fildf_y = fildf.loc[:,yfeatures]

In [12]:
fildf_x.shape

(882, 32)

In [13]:
fildf_y.shape

(882, 32)

In [14]:
def convertmarks(mark):
    if mark<10:
        return 'B'
    else:
        return 'A'

In [15]:
newlist=[]
for i in fildf_x['G1.x']:
    x = convertmarks(i)
    newlist.append(x)
fildf_x['New G1'] = newlist

In [16]:
newlist=[]
for i in fildf_y['G1.y']:
    x = convertmarks(i)
    newlist.append(x)
fildf_y['New G1'] = newlist

In [17]:
newlist=[]
for i in fildf_x['G3.x']:
    x = convertmarks(i)
    newlist.append(x)
fildf_x['New G3'] = newlist

In [18]:
newlist=[]
for i in fildf_y['G3.y']:
    x = convertmarks(i)
    newlist.append(x)
fildf_y['New G3'] = newlist

In [19]:
fildf_y['New G3']

0      A
1      A
2      A
3      A
4      A
      ..
877    A
878    A
879    A
880    A
881    A
Name: New G3, Length: 882, dtype: object

In [20]:
label_encoder = preprocessing.LabelEncoder()

In [21]:
fildf_x['New G1']= label_encoder.fit_transform(fildf_x['New G1'])
fildf_y['New G1']= label_encoder.fit_transform(fildf_y['New G1'])
fildf_x['New G3']= label_encoder.fit_transform(fildf_x['New G3'])
fildf_y['New G3']= label_encoder.fit_transform(fildf_y['New G3'])

In [22]:
fildf_y['New G3']

0      0
1      0
2      0
3      0
4      0
      ..
877    0
878    0
879    0
880    0
881    0
Name: New G3, Length: 882, dtype: int64

In [23]:
fildf_x = fildf_x.sample(frac=1,random_state=123)
fildf_y = fildf_y.sample(frac=1,random_state=123)

In [24]:
fildf_x['New G1'].value_counts()

0    665
1    217
Name: New G1, dtype: int64

In [25]:
fildf_x['New G3'].value_counts()

0    606
1    276
Name: New G3, dtype: int64

In [26]:
max_size = fildf_x['New G1'].value_counts().min()

In [27]:
max_size

217

In [28]:
lst = [fildf_x]
lst1=[]
for class_index, group in fildf_x.groupby('New G1'):
    lst1.append(group.sample(max_size, replace=True))
fildf_x_G1 = pd.concat(lst1)

In [29]:
fildf_x_G1['New G1'].value_counts()

1    217
0    217
Name: New G1, dtype: int64

In [30]:
max_size = fildf_y['New G1'].value_counts().min()

In [31]:
print(max_size)

69


In [32]:
lst = [fildf_y]
lst1=[]
for class_index, group in fildf_y.groupby('New G1'):
    lst1.append(group.sample(max_size, replace=True))
fildf_y_G1 = pd.concat(lst1)

In [33]:
fildf_y_G1['New G1'].value_counts()

1    69
0    69
Name: New G1, dtype: int64

In [34]:
max_size = fildf_x['New G3'].value_counts().min()

In [35]:
lst = [fildf_x]
lst1=[]
for class_index, group in fildf_x.groupby('New G3'):
    lst1.append(group.sample(max_size, replace=True))
fildf_x_G3 = pd.concat(lst1)

In [36]:
fildf_x_G3['New G3'].value_counts()

1    276
0    276
Name: New G3, dtype: int64

In [37]:
max_size = fildf_y['New G3'].value_counts().min()

In [38]:
lst = [fildf_y]
lst1=[]
for class_index, group in fildf_y.groupby('New G3'):
    lst1.append(group.sample(max_size, replace=True))
fildf_y_G3 = pd.concat(lst1)

In [39]:
fildf_y_G3['New G3'].value_counts()

1    46
0    46
Name: New G3, dtype: int64

In [40]:
fildf_y_G3.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.y',
       'traveltime.y', 'studytime.y', 'failures.y', 'schoolsup.y', 'famsup.y',
       'paid.y', 'activities.y', 'higher.y', 'romantic.y', 'famrel.y',
       'freetime.y', 'goout.y', 'Dalc.y', 'Walc.y', 'health.y', 'absences.y',
       'G1.y', 'G3.y', 'New G1', 'New G3'],
      dtype='object')

In [41]:
fildf_x_G1 = fildf_x_G1.drop(['G1.x','G3.x'],axis=1)
fildf_y_G1 = fildf_y_G1.drop(['G1.y','G3.y'],axis=1)
fildf_x_G3 = fildf_x_G3.drop(['G1.x','G3.x'],axis=1)
fildf_y_G3 = fildf_y_G3.drop(['G1.y','G3.y'],axis=1)

In [42]:
features_x_G3 = fildf_x_G3.drop(['New G1','New G3'],axis=1)
features_x_G1 = fildf_x_G1.drop(['New G1','New G3'],axis=1)
features_y_G3 = fildf_y_G3.drop(['New G1','New G3'],axis=1)
features_y_G1 = fildf_y_G1.drop(['New G1','New G3'],axis=1)

In [43]:
target_x_G3 = fildf_x_G3['New G3']
target_x_G1 = fildf_x_G1['New G1']
target_y_G3 = fildf_y_G3['New G3']
target_y_G1 = fildf_y_G1['New G1']

In [44]:
X_train_x_G1, X_test_x_G1, y_train_x_G1, y_test_x_G1 = train_test_split(features_x_G1, target_x_G1, test_size=0.25, random_state=0)
X_train_y_G1, X_test_y_G1, y_train_y_G1, y_test_y_G1 = train_test_split(features_y_G1, target_y_G1, test_size=0.25, random_state=0)

In [45]:
X_train_x_G3, X_test_x_G3, y_train_x_G3, y_test_x_G3 = train_test_split(features_x_G3, target_x_G3, test_size=0.25, random_state=0)
X_train_y_G3, X_test_y_G3, y_train_y_G3, y_test_y_G3 = train_test_split(features_y_G3, target_y_G3, test_size=0.25, random_state=0)

### SVM

In [46]:
param_grid_svc = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001],'kernel': ['linear','rbf', 'poly', 'sigmoid']}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [47]:
#grid_svc_x_G1 = GridSearchCV(SVC(),param_grid = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G1 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_svc_x_G1.best_estimator_)
y_pred_x_G1= grid_svc_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    2.3s


SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.81      0.87      0.84        54
           1       0.86      0.80      0.83        55

    accuracy                           0.83       109
   macro avg       0.84      0.84      0.83       109
weighted avg       0.84      0.83      0.83       109

[[47 11]
 [ 7 44]]
Kappa Score: 0.6699192462987886


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   18.0s finished


In [48]:
grid_svc_x_G3 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_svc_x_G3.best_estimator_)
y_pred_x_G3= grid_svc_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Done 106 tasks      | elapsed:    0.7s


SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.82      0.75      0.78        67
           1       0.78      0.85      0.81        71

    accuracy                           0.80       138
   macro avg       0.80      0.80      0.80       138
weighted avg       0.80      0.80      0.80       138

[[50 11]
 [17 60]]
Kappa Score: 0.5928345626975764


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   27.4s finished


In [49]:
grid_svc_y_G1 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_svc_y_G1.best_estimator_)
y_pred_y_G1= grid_svc_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 10 candidates, totalling 300 fits
SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.86      0.90      0.88        20
           1       0.86      0.80      0.83        15

    accuracy                           0.86        35
   macro avg       0.86      0.85      0.85        35
weighted avg       0.86      0.86      0.86        35

[[18  3]
 [ 2 12]]
Kappa Score: 0.7058823529411764


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    0.6s finished


In [50]:
grid_svc_y_G3 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_svc_y_G3.best_estimator_)
y_pred_y_G3= grid_svc_y_G3.predict(X_test_y_G3)
print(metrics.classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 10 candidates, totalling 300 fits
SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.93      0.81      0.87        16
           1       0.67      0.86      0.75         7

    accuracy                           0.83        23
   macro avg       0.80      0.83      0.81        23
weighted avg       0.85      0.83      0.83        23

[[13  1]
 [ 3  6]]
Kappa Score: 0.6198347107438017


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    0.7s finished


### Gradient Boosting

In [51]:
gbc = GradientBoostingClassifier()
parameters_gbc = {
    "n_estimators":[5,50,250,500],
    "max_depth":[1,3,5,7,9],
    "learning_rate":[0.01,0.1,1,10,100]
}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [52]:
grid_gbc_x_G1 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_gbc_x_G1.best_estimator_)
y_pred_x_G1= grid_gbc_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    1.2s
[Parallel(n_jobs=-1)]: Done 285 out of 300 | elapsed:   22.6s remaining:    1.2s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   23.6s finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.01, loss='deviance', max_depth=7,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        58
           1       0.92      0.92      0.92        51

    accuracy                           0.93       109
   macro avg       0.93      0.93      0.93       109
weighted avg       0.93      0

In [53]:
grid_gbc_x_G3 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_gbc_x_G3.best_estimator_)
y_pred_x_G3= grid_gbc_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   40.2s finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.01, loss='deviance', max_depth=5,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=250,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.95      0.78      0.86        74
           1       0.79      0.95      0.87        64

    accuracy                           0.86       138
   macro avg       0.87      0.87      0.86       138
weighted avg       0.88      0

In [54]:
grid_gbc_y_G1 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_gbc_y_G1.best_estimator_)
y_pred_y_G1= grid_gbc_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    1.4s


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=1,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=250,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.81      1.00      0.89        17
           1       1.00      0.78      0.88        18

    accuracy                           0.89        35
   macro avg       0.90      0.89      0.88        35
weighted avg       0.91      0.

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    9.0s finished


In [55]:
grid_gbc_y_G3 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_gbc_y_G3.best_estimator_)
y_pred_y_G3= grid_gbc_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    0.7s


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.01, loss='deviance', max_depth=1,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.86      0.86      0.86        14
           1       0.78      0.78      0.78         9

    accuracy                           0.83        23
   macro avg       0.82      0.82      0.82        23
weighted avg       0.83      0

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    4.4s finished


### Logistic Regression

In [56]:
lr = LogisticRegression(max_iter=1000)
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [10, 1.0, 0.1, 0.01]
grid = dict(solver=solvers,penalty=penalty,C=c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [57]:
grid_search_lr_x_G1 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_lr_x_G1.best_estimator_)
y_pred_x_G1= grid_search_lr_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.90      0.85      0.87        61
           1       0.82      0.88      0.85        48

    accuracy                           0.86       109
   macro avg       0.86      0.86      0.86       109
weighted avg       0.86      0.86      0.86       109

[[52  6]
 [ 9 42]]
Kappa Score: 0.72264631043257


In [58]:
grid_search_lr_x_G3 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_lr_x_G3.best_estimator_)
y_pred_x_G3= grid_search_lr_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.85      0.74      0.79        70
           1       0.77      0.87      0.81        68

    accuracy                           0.80       138
   macro avg       0.81      0.81      0.80       138
weighted avg       0.81      0.80      0.80       138

[[52  9]
 [18 59]]
Kappa Score: 0.6093520654225204


In [59]:
grid_search_lr_y_G1 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_lr_y_G1.best_estimator_)
y_pred_y_G1= grid_search_lr_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.76      0.89      0.82        18
           1       0.86      0.71      0.77        17

    accuracy                           0.80        35
   macro avg       0.81      0.80      0.80        35
weighted avg       0.81      0.80      0.80        35

[[16  5]
 [ 2 12]]
Kappa Score: 0.5977011494252873


In [60]:
grid_search_lr_y_G3 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_lr_y_G3.best_estimator_)
y_pred_y_G3= grid_search_lr_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.93      0.81      0.87        16
           1       0.67      0.86      0.75         7

    accuracy                           0.83        23
   macro avg       0.80      0.83      0.81        23
weighted avg       0.85      0.83      0.83        23

[[13  1]
 [ 3  6]]
Kappa Score: 0.6198347107438017


### Random Forest

In [61]:
# define models and parameters
rf = RandomForestClassifier()
n_estimators = [10, 100, 1000]
max_features = ['sqrt', 'log2']
# define grid search
grid = dict(n_estimators=n_estimators,max_features=max_features)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [62]:
grid_search_rf_x_G1 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_rf_x_G1.best_estimator_)
y_pred_x_G1= grid_search_rf_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.91      0.93      0.92        57
           1       0.92      0.90      0.91        52

    accuracy                           0.92       109
   macro avg       0.92      0.92      0.92       109
weighted avg       0.92      0.92      0.92       109

[[53  5]
 [ 4 47]]
Kappa Score: 0.8343744723957454


In [63]:
grid_search_rf_x_G3 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_rf_x_G3.best_estimator_)
y_pred_x_G3= grid_search_rf_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.90      0.83      0.87        66
           1       0.86      0.92      0.89        72

    accuracy                           0.88       138
   macro avg       0.88      0.88      0.88       138
weighted avg       0.88      0.88      0.88       138

[[55  6]
 [11 66]]
Kappa Score: 0.7523749208359721


In [64]:
grid_search_rf_y_G1 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_rf_y_G1.best_estimator_)
y_pred_y_G1= grid_search_rf_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.81      1.00      0.89        17
           1       1.00      0.78      0.88        18

    accuracy                           0.89        35
   macro avg       0.90      0.89      0.88        35
weighted avg       0.91      0.89      0.88        35

[[17  4]
 [ 0 14]]
Kappa Score: 0.7727272727272727


In [65]:
grid_search_rf_y_G3 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_rf_y_G3.best_estimator_)
y_pred_y_G3= grid_search_rf_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.89      1.00      0.94         8

    accuracy                           0.96        23
   macro avg       0.94      0.97      0.95        23
weighted avg       0.96      0.96      0.96        23

[[14  0]
 [ 1  8]]
Kappa Score: 0.9068825910931174


### Decision Tree

In [66]:
dct = DecisionTreeClassifier()
param_dist = {"max_depth": [1,2,3,4,5],
              "max_features": ['auto', 'sqrt', 'log2'],
              "min_samples_leaf": [1,2,3,4,5],
              "min_samples_split" : [1,2,3,4,5],
              "criterion": ["gini", "entropy"]}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [67]:
grid_search_dct_x_G1 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_dct_x_G1.best_estimator_)
y_pred_x_G1= grid_search_dct_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features='log2', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.60      0.78      0.68        45
           1       0.80      0.64      0.71        64

    accuracy                           0.70       109
   macro avg       0.70      0.71      0.70       109
weighted avg       0.72      0.70      0.70       109

[[35 23]
 [10 41]]
Kappa Score: 0.40119860163143006


In [68]:
grid_search_dct_x_G3 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_dct_x_G3.best_estimator_)
y_pred_x_G3= grid_search_dct_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=5, max_features='log2', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.79      0.55      0.64        88
           1       0.48      0.74      0.58        50

    accuracy                           0.62       138
   macro avg       0.63      0.64      0.61       138
weighted avg       0.68      0.62      0.62       138

[[48 13]
 [40 37]]
Kappa Score: 0.255648280073275


In [69]:
grid_search_dct_y_G1 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_dct_y_G1.best_estimator_)
y_pred_y_G1= grid_search_dct_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=5, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.52      0.85      0.65        13
           1       0.86      0.55      0.67        22

    accuracy                           0.66        35
   macro avg       0.69      0.70      0.66        35
weighted avg       0.73      0.66      0.66        35

[[11 10]
 [ 2 12]]
Kappa Score: 0.34782608695652173


In [70]:
grid_search_dct_y_G3 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_dct_y_G3.best_estimator_)
y_pred_y_G3= grid_search_rf_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=5, max_features='log2', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.89      1.00      0.94         8

    accuracy                           0.96        23
   macro avg       0.94      0.97      0.95        23
weighted avg       0.96      0.96      0.96        23

[[14  0]
 [ 1  8]]
Kappa Score: 0.9068825910931174


### Gaussian Naive Bayesian

In [71]:
clf = GaussianNB()

In [72]:
clf.fit(X_train_x_G1,y_train_x_G1)
y_pred_x_G1= clf.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))
probagnbG1x = clf.predict_proba(X_test_x_G1)

              precision    recall  f1-score   support

           0       0.88      0.86      0.87        59
           1       0.84      0.86      0.85        50

    accuracy                           0.86       109
   macro avg       0.86      0.86      0.86       109
weighted avg       0.86      0.86      0.86       109

Kappa Score: 0.7233034354374683


In [73]:
clf.fit(X_train_x_G3,y_train_x_G3)
y_pred_x_G3= clf.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))
probagnbG3x = clf.predict_proba(X_test_x_G3)

              precision    recall  f1-score   support

           0       0.85      0.73      0.79        71
           1       0.75      0.87      0.81        67

    accuracy                           0.80       138
   macro avg       0.80      0.80      0.80       138
weighted avg       0.80      0.80      0.80       138

Kappa Score: 0.5955620682436675


In [74]:
clf.fit(X_train_y_G1,y_train_y_G1)
y_pred_y_G1 = clf.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))
probagnbG1y = clf.predict_proba(X_test_y_G1)

              precision    recall  f1-score   support

           0       0.76      0.84      0.80        19
           1       0.79      0.69      0.73        16

    accuracy                           0.77        35
   macro avg       0.77      0.76      0.77        35
weighted avg       0.77      0.77      0.77        35

Kappa Score: 0.5348837209302326


In [75]:
clf.fit(X_train_y_G3,y_train_y_G3)
y_pred_y_G3 = clf.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))
probagnbG3y = clf.predict_proba(X_test_y_G3)

              precision    recall  f1-score   support

           0       0.71      0.71      0.71        14
           1       0.56      0.56      0.56         9

    accuracy                           0.65        23
   macro avg       0.63      0.63      0.63        23
weighted avg       0.65      0.65      0.65        23

Kappa Score: 0.2698412698412699
