In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import cohen_kappa_score
import matplotlib.pyplot as plt
from scipy.stats import rankdata
import imblearn
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import RepeatedStratifiedKFold
from scipy.stats import randint

Using TensorFlow backend.


In [2]:
df = pd.read_csv('final_combined_dataset.csv')

In [3]:
df.head()

school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob  Fjob  ...  \
0       0    0   15        0        0        1     1     1     0     2  ...   
1       0    0   15        0        0        1     1     1     2     2  ...   
2       0    0   15        0        0        1     2     2     0     2  ...   
3       0    0   15        0        0        1     2     4     3     1  ...   
4       0    0   15        0        0        1     3     3     3     3  ...   

   famrel.y  freetime.y  goout.y  Dalc.y  Walc.y  health.y  absences.y  G1.y  \
0         3           1        2       1       1         1           4    13   
1         3           3        4       2       4         5           2    13   
2         4           3        1       1       1         2           8    14   
3         4           3        2       1       1         5           2    10   
4         4           2        1       2       3         3           2    13   

   G2.y  G3.y  
0    13    13  
1    11    11  
2    13    12  
3    11    10  
4    13    13  

[5 rows x 53 columns]

In [4]:
df = df.rename(columns = {'Unnamed: 0':'ID'})

In [5]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x',
       'G1.x', 'G2.x', 'G3.x', 'guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y', 'G1.y', 'G2.y', 'G3.y'],
      dtype='object')

In [6]:
xfeatures=['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x','G1.x','G3.x']

In [7]:
yfeatures = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet','guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y','G1.y','G3.y']

In [8]:
keepcol = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu',
       'Fedu', 'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.x',
       'traveltime.x', 'studytime.x', 'failures.x', 'schoolsup.x', 'famsup.x',
       'paid.x', 'activities.x', 'higher.x', 'romantic.x', 'famrel.x',
       'freetime.x', 'goout.x', 'Dalc.x', 'Walc.x', 'health.x', 'absences.x',
       'G1.x', 'G2.x', 'G3.x', 'guardian.y', 'traveltime.y', 'studytime.y',
       'failures.y', 'schoolsup.y', 'famsup.y', 'paid.y', 'activities.y',
       'higher.y', 'romantic.y', 'famrel.y', 'freetime.y', 'goout.y', 'Dalc.y',
       'Walc.y', 'health.y', 'absences.y', 'G1.y', 'G2.y', 'G3.y']

In [9]:
fildf = df.loc[:,keepcol]

In [10]:
fildf_x = fildf.loc[:,xfeatures]

In [11]:
fildf_y = fildf.loc[:,yfeatures]

In [12]:
fildf_x.shape

(882, 32)

In [13]:
fildf_y.shape

(882, 32)

In [14]:
def convertmarks(mark):
    if mark<10:
        return 'F'
    elif mark==10 or mark==11:
        return 'D'
    elif mark==12 or mark==13:
        return 'C'
    elif mark==14 or mark==15:
        return'B'
    else:
        return 'A'

In [15]:
newlist=[]
for i in fildf_x['G1.x']:
    x = convertmarks(i)
    newlist.append(x)
fildf_x['New G1'] = newlist

In [16]:
newlist=[]
for i in fildf_y['G1.y']:
    x = convertmarks(i)
    newlist.append(x)
fildf_y['New G1'] = newlist

In [17]:
newlist=[]
for i in fildf_x['G3.x']:
    x = convertmarks(i)
    newlist.append(x)
fildf_x['New G3'] = newlist

In [18]:
newlist=[]
for i in fildf_y['G3.y']:
    x = convertmarks(i)
    newlist.append(x)
fildf_y['New G3'] = newlist

In [19]:
fildf_y['New G3']

0      C
1      D
2      C
3      D
4      C
      ..
877    C
878    B
879    C
880    C
881    C
Name: New G3, Length: 882, dtype: object

In [20]:
label_encoder = preprocessing.LabelEncoder()

In [21]:
fildf_x['New G1']= label_encoder.fit_transform(fildf_x['New G1'])
fildf_y['New G1']= label_encoder.fit_transform(fildf_y['New G1'])
fildf_x['New G3']= label_encoder.fit_transform(fildf_x['New G3'])
fildf_y['New G3']= label_encoder.fit_transform(fildf_y['New G3'])

In [22]:
fildf_y['New G3']

0      2
1      3
2      2
3      3
4      2
      ..
877    2
878    1
879    2
880    2
881    2
Name: New G3, Length: 882, dtype: int64

In [23]:
fildf_x = fildf_x.sample(frac=1,random_state=123)
fildf_y = fildf_y.sample(frac=1,random_state=123)

In [24]:
fildf_x['New G1'].value_counts()

2    413
4    217
3    161
1     49
0     42
Name: New G1, dtype: int64

In [25]:
fildf_x['New G3'].value_counts()

2    406
4    276
3     99
1     59
0     42
Name: New G3, dtype: int64

In [26]:
max_size = fildf_x['New G1'].value_counts().min()

In [27]:
max_size

42

In [28]:
lst = [fildf_x]
lst1=[]
for class_index, group in fildf_x.groupby('New G1'):
    lst1.append(group.sample(max_size, replace=True))
fildf_x_G1 = pd.concat(lst1)

In [29]:
fildf_x_G1['New G1'].value_counts()

4    42
3    42
2    42
1    42
0    42
Name: New G1, dtype: int64

In [30]:
max_size = fildf_y['New G1'].value_counts().min()

In [31]:
print(max_size)

36


In [32]:
lst = [fildf_y]
lst1=[]
for class_index, group in fildf_y.groupby('New G1'):
    lst1.append(group.sample(max_size, replace=True))
fildf_y_G1 = pd.concat(lst1)

In [33]:
fildf_y_G1['New G1'].value_counts()

4    36
3    36
2    36
1    36
0    36
Name: New G1, dtype: int64

In [34]:
max_size = fildf_x['New G3'].value_counts().min()

In [35]:
lst = [fildf_x]
lst1=[]
for class_index, group in fildf_x.groupby('New G3'):
    lst1.append(group.sample(max_size, replace=True))
fildf_x_G3 = pd.concat(lst1)

In [36]:
fildf_x_G3['New G3'].value_counts()

4    42
3    42
2    42
1    42
0    42
Name: New G3, dtype: int64

In [37]:
max_size = fildf_y['New G3'].value_counts().min()

In [38]:
lst = [fildf_y]
lst1=[]
for class_index, group in fildf_y.groupby('New G3'):
    lst1.append(group.sample(max_size, replace=True))
fildf_y_G3 = pd.concat(lst1)

In [39]:
fildf_y_G3['New G3'].value_counts()

4    46
3    46
2    46
1    46
0    46
Name: New G3, dtype: int64

In [40]:
fildf_y_G3.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian.y',
       'traveltime.y', 'studytime.y', 'failures.y', 'schoolsup.y', 'famsup.y',
       'paid.y', 'activities.y', 'higher.y', 'romantic.y', 'famrel.y',
       'freetime.y', 'goout.y', 'Dalc.y', 'Walc.y', 'health.y', 'absences.y',
       'G1.y', 'G3.y', 'New G1', 'New G3'],
      dtype='object')

In [41]:
fildf_x_G1 = fildf_x_G1.drop(['G1.x','G3.x'],axis=1)
fildf_y_G1 = fildf_y_G1.drop(['G1.y','G3.y'],axis=1)
fildf_x_G3 = fildf_x_G3.drop(['G1.x','G3.x'],axis=1)
fildf_y_G3 = fildf_y_G3.drop(['G1.y','G3.y'],axis=1)

In [42]:
features_x_G3 = fildf_x_G3.drop(['New G1','New G3'],axis=1)
features_x_G1 = fildf_x_G1.drop(['New G1','New G3'],axis=1)
features_y_G3 = fildf_y_G3.drop(['New G1','New G3'],axis=1)
features_y_G1 = fildf_y_G1.drop(['New G1','New G3'],axis=1)

In [43]:
target_x_G3 = fildf_x_G3['New G3']
target_x_G1 = fildf_x_G1['New G1']
target_y_G3 = fildf_y_G3['New G3']
target_y_G1 = fildf_y_G1['New G1']

In [44]:
X_train_x_G1, X_test_x_G1, y_train_x_G1, y_test_x_G1 = train_test_split(features_x_G1, target_x_G1, test_size=0.25, random_state=0)
X_train_y_G1, X_test_y_G1, y_train_y_G1, y_test_y_G1 = train_test_split(features_y_G1, target_y_G1, test_size=0.25, random_state=0)

In [45]:
X_train_x_G3, X_test_x_G3, y_train_x_G3, y_test_x_G3 = train_test_split(features_x_G3, target_x_G3, test_size=0.25, random_state=0)
X_train_y_G3, X_test_y_G3, y_train_y_G3, y_test_y_G3 = train_test_split(features_y_G3, target_y_G3, test_size=0.25, random_state=0)

### SVM

In [46]:
param_grid_svc = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001],'kernel': ['linear','rbf', 'poly', 'sigmoid']}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [47]:
#grid_svc_x_G1 = GridSearchCV(SVC(),param_grid = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G1 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_svc_x_G1.best_estimator_)
y_pred_x_G1= grid_svc_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    2.1s


SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.36      0.36      0.36        11
           1       0.36      0.40      0.38        10
           2       0.42      0.42      0.42        12
           3       0.27      0.38      0.32         8
           4       0.75      0.50      0.60        12

    accuracy                           0.42        53
   macro avg       0.43      0.41      0.42        53
weighted avg       0.45      0.42      0.43        53

[[4 2 3 0 2]
 [2 4 3 0 2]
 [2 1 5 4 0]
 [3 2 1 3 2]
 [0 1 0 1 6]]
Kappa Score: 0.2697777777777778


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    2.5s finished


In [48]:
grid_svc_x_G3 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_svc_x_G3.best_estimator_)
y_pred_x_G3= grid_svc_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 10 candidates, totalling 300 fits
SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)
              precision    recall  f1-score   support

           0       0.82      1.00      0.90         9
           1       0.27      1.00      0.43         3
           2       0.08      1.00      0.15         1
           3       0.27      1.00      0.43         3
           4       1.00      0.22      0.36        37

    accuracy                           0.45        53
   macro avg       0.49      0.84      0.45        53
weighted avg       0.87      0.45      0.45        53

[[ 9  0  0  0  2]
 [ 0  3  0  0  8]
 [ 0  0  1  0 11]
 [ 0  0  0  3  8]
 [ 0  0  0  0  8]]
Kappa Score: 0.34203767123287676


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    0.5s finished


In [49]:
grid_svc_y_G1 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_svc_y_G1.best_estimator_)
y_pred_y_G1= grid_svc_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 10 candidates, totalling 300 fits
SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         6
           1       0.18      0.40      0.25         5
           2       0.50      0.21      0.30        14
           3       0.50      0.31      0.38        13
           4       0.45      0.71      0.56         7

    accuracy                           0.44        45
   macro avg       0.46      0.53      0.46        45
weighted avg       0.48      0.44      0.42        45

[[6 0 3 0 0]
 [0 2 3 5 1]
 [0 2 3 1 0]
 [0 1 2 4 1]
 [0 0 3 3 5]]
Kappa Score: 0.31859479103573585


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    1.1s finished


In [50]:
grid_svc_y_G3 = RandomizedSearchCV(SVC(),param_distributions = param_grid_svc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_svc_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_svc_y_G3.best_estimator_)
y_pred_y_G3= grid_svc_y_G3.predict(X_test_y_G3)
print(metrics.classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 10 candidates, totalling 300 fits
SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
              precision    recall  f1-score   support

           0       0.40      0.40      0.40        10
           1       0.29      0.18      0.22        11
           2       0.43      0.40      0.41        15
           3       0.33      0.71      0.45         7
           4       0.83      0.67      0.74        15

    accuracy                           0.47        58
   macro avg       0.46      0.47      0.45        58
weighted avg       0.49      0.47      0.46        58

[[ 4  3  2  0  1]
 [ 3  2  2  0  0]
 [ 2  4  6  2  0]
 [ 1  2  3  5  4]
 [ 0  0  2  0 10]]
Kappa Score: 0.3320950965824665


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    0.9s finished


### Gradient Boosting

In [51]:
gbc = GradientBoostingClassifier()
parameters_gbc = {
    "n_estimators":[5,50,250,500],
    "max_depth":[1,3,5,7,9],
    "learning_rate":[0.01,0.1,1,10,100]
}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [52]:
grid_gbc_x_G1 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_gbc_x_G1.best_estimator_)
y_pred_x_G1= grid_gbc_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   19.4s
[Parallel(n_jobs=-1)]: Done 168 tasks      | elapsed:   30.7s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  1.1min finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.01, loss='deviance', max_depth=5,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=250,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.36      0.57      0.44         7
           1       0.18      0.33      0.24         6
           2       0.33      0.31      0.32        13
           3       0.64      0.58      0.61        12
           4       0.75      0.

In [53]:
grid_gbc_x_G3 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_gbc_x_G3.best_estimator_)
y_pred_x_G3= grid_gbc_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    8.2s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   26.7s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   50.6s finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=250,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.82      0.60      0.69        15
           1       0.36      0.44      0.40         9
           2       0.17      0.20      0.18        10
           3       0.36      0.44      0.40         9
           4       0.62      0.50 

In [54]:
grid_gbc_y_G1 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_gbc_y_G1.best_estimator_)
y_pred_y_G1= grid_gbc_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    2.3s
[Parallel(n_jobs=-1)]: Done 199 tasks      | elapsed:   14.8s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   24.2s finished


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=9,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=50,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.67      0.50      0.57        12
           1       0.45      0.62      0.53         8
           2       0.50      0.43      0.46         7
           3       0.75      0.60      0.67        10
           4       0.73      1.00

In [55]:
grid_gbc_y_G3 = RandomizedSearchCV(gbc,param_distributions = parameters_gbc,refit=True,verbose=2,n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_gbc_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_gbc_y_G3.best_estimator_)
y_pred_y_G3= grid_gbc_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

Fitting 30 folds for each of 10 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  52 tasks      | elapsed:    1.1s


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=1, loss='deviance', max_depth=5,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=50,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
              precision    recall  f1-score   support

           0       0.40      0.50      0.44         8
           1       0.57      0.33      0.42        12
           2       0.36      0.33      0.34        15
           3       0.20      0.38      0.26         8
           4       0.75      0.60  

[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    5.6s finished


### Logistic Regression

In [56]:
lr = LogisticRegression(max_iter=1000)
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [10, 1.0, 0.1, 0.01]
grid = dict(solver=solvers,penalty=penalty,C=c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [57]:
grid_search_lr_x_G1 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_lr_x_G1.best_estimator_)
y_pred_x_G1= grid_search_lr_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.45      0.33      0.38        15
           1       0.18      0.22      0.20         9
           2       0.42      0.42      0.42        12
           3       0.18      0.67      0.29         3
           4       0.88      0.50      0.64        14

    accuracy                           0.40        53
   macro avg       0.42      0.43      0.38        53
weighted avg       0.50      0.40      0.42        53

[[5 2 3 0 1]
 [3 2 4 0 2]
 [3 1 5 1 2]
 [4 3 0 2 2]
 [0 1 0 0 7]]
Kappa Score: 0.24822695035460995


In [58]:
grid_search_lr_x_G3 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_lr_x_G3.best_estimator_)
y_pred_x_G3= grid_search_lr_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.55      0.46      0.50        13
           1       0.55      0.46      0.50        13
           2       0.50      0.50      0.50        12
           3       0.27      0.60      0.37         5
           4       0.38      0.30      0.33        10

    accuracy                           0.45        53
   macro avg       0.45      0.46      0.44        53
weighted avg       0.48      0.45      0.46        53

[[6 3 2 0 0]
 [1 6 3 0 1]
 [2 0 6 1 3]
 [1 3 1 3 3]
 [3 1 0 1 3]]
Kappa Score: 0.31506238859180036


In [59]:
grid_search_lr_y_G1 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_lr_y_G1.best_estimator_)
y_pred_y_G1= grid_search_lr_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.56      0.50      0.53        10
           1       0.64      0.88      0.74         8
           2       0.33      0.29      0.31         7
           3       0.50      0.40      0.44        10
           4       0.64      0.70      0.67        10

    accuracy                           0.56        45
   macro avg       0.53      0.55      0.54        45
weighted avg       0.54      0.56      0.54        45

[[5 0 2 1 1]
 [1 7 1 2 0]
 [3 0 2 1 0]
 [1 1 0 4 2]
 [0 0 2 2 7]]
Kappa Score: 0.44272445820433437


In [60]:
grid_search_lr_y_G3 = RandomizedSearchCV(estimator=lr, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_lr_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_lr_y_G3.best_estimator_)
y_pred_y_G3= grid_search_lr_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)
              precision    recall  f1-score   support

           0       0.30      0.33      0.32         9
           1       0.43      0.27      0.33        11
           2       0.29      0.33      0.31        12
           3       0.40      0.67      0.50         9
           4       0.83      0.59      0.69        17

    accuracy                           0.45        58
   macro avg       0.45      0.44      0.43        58
weighted avg       0.49      0.45      0.46        58

[[ 3  4  2  0  1]
 [ 1  3  2  0  1]
 [ 4  3  4  3  0]
 [ 1  1  2  6  5]
 [ 0  0  2  0 10]]
Kappa Score: 0.3100371747211895


### Random Forest

In [61]:
# define models and parameters
rf = RandomForestClassifier()
n_estimators = [10, 100, 1000]
max_features = ['sqrt', 'log2']
# define grid search
grid = dict(n_estimators=n_estimators,max_features=max_features)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [62]:
grid_search_rf_x_G1 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_rf_x_G1.best_estimator_)
y_pred_x_G1= grid_search_rf_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.36      0.50      0.42         8
           1       0.45      0.45      0.45        11
           2       0.50      0.43      0.46        14
           3       0.36      0.57      0.44         7
           4       0.88      0.54      0.67        13

    accuracy                           0.49        53
   macro avg       0.51      0.50      0.49        53
weighted avg      

In [63]:
grid_search_rf_x_G3 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_rf_x_G3.best_estimator_)
y_pred_x_G3= grid_search_rf_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.91      0.62      0.74        16
           1       0.45      0.56      0.50         9
           2       0.17      0.29      0.21         7
           3       0.45      0.62      0.53         8
           4       0.88      0.54      0.67        13

    accuracy                           0.55        53
   macro avg       0.57      0.53      0.53        53
weighted avg       

In [64]:
grid_search_rf_y_G1 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_rf_y_G1.best_estimator_)
y_pred_y_G1= grid_search_rf_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.89      0.67      0.76        12
           1       0.36      0.50      0.42         8
           2       0.33      0.20      0.25        10
           3       0.62      0.62      0.62         8
           4       0.64      1.00      0.78         7

    accuracy                           0.58        45
   macro avg       0.57      0.60      0.57        45
weighted avg      

In [65]:
grid_search_rf_y_G3 = RandomizedSearchCV(estimator=rf, param_distributions=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_rf_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_rf_y_G3.best_estimator_)
y_pred_y_G3= grid_search_rf_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
              precision    recall  f1-score   support

           0       0.30      0.50      0.37         6
           1       0.57      0.29      0.38        14
           2       0.29      0.33      0.31        12
           3       0.40      0.75      0.52         8
           4       0.92      0.61      0.73        18

    accuracy                           0.48        58
   macro avg       0.49      0.50      0.46        58
weighted avg      

### Decision Tree

In [66]:
dct = DecisionTreeClassifier()
param_dist = {"max_depth": [1,2,3,4,5],
              "max_features": ['auto', 'sqrt', 'log2'],
              "min_samples_leaf": [1,2,3,4,5],
              "min_samples_split" : [1,2,3,4,5],
              "criterion": ["gini", "entropy"]}
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [67]:
grid_search_dct_x_G1 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_x_G1.fit(X_train_x_G1,y_train_x_G1)
print(grid_search_dct_x_G1.best_estimator_)
y_pred_x_G1= grid_search_dct_x_G1.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1,zero_division='warn'))
print(confusion_matrix(y_test_x_G1,y_pred_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.64      0.39      0.48        18
           1       0.64      0.41      0.50        17
           2       0.08      0.33      0.13         3
           3       0.36      0.67      0.47         6
           4       0.75      0.67      0.71         9

    accuracy                           0.47        53
   macro avg       0.49      0.49      0.46        53
weighted avg       0.59      0.47      0.51        53

[[7 2 1 1 0]
 [1 7 1 0 2]
 [5 5 1 1 0]
 [4 2 0 4 1]
 [1 1 0 0 6]]
Kappa Score: 0.3404

In [68]:
grid_search_dct_x_G3 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_x_G3.fit(X_train_x_G3,y_train_x_G3)
print(grid_search_dct_x_G3.best_estimator_)
y_pred_x_G3= grid_search_dct_x_G3.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3,zero_division='warn'))
print(confusion_matrix(y_test_x_G3,y_pred_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=4, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.36      0.31      0.33        13
           1       0.64      0.37      0.47        19
           2       0.00      0.00      0.00         0
           3       0.45      0.31      0.37        16
           4       0.12      0.20      0.15         5

    accuracy                           0.32        53
   macro avg       0.32      0.24      0.26        53
weighted avg       0.47      0.32      0.38        53

[[4 4 0 3 0]
 [0 7 0 2 2]
 [7 1 0 4 0]
 [1 3 0 5 2]
 [1 4 0 2 1]]
Kappa Score: 0.1485

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [69]:
grid_search_dct_y_G1 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_y_G1.fit(X_train_y_G1,y_train_y_G1)
print(grid_search_dct_y_G1.best_estimator_)
y_pred_y_G1= grid_search_dct_y_G1.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1,zero_division='warn'))
print(confusion_matrix(y_test_y_G1,y_pred_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features='log2', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.44      0.40      0.42        10
           1       0.36      0.31      0.33        13
           2       0.50      0.21      0.30        14
           3       0.12      0.20      0.15         5
           4       0.27      1.00      0.43         3

    accuracy                           0.33        45
   macro avg       0.34      0.42      0.33        45
weighted avg       0.39      0.33      0.33        45

[[4 3 2 0 0]
 [3 4 2 2 0]
 [1 2 3 0 0]
 [2 3 2 1 0]
 [0 1 5 2 3]]
Kappa Score: 0.1743

In [70]:
grid_search_dct_y_G3 = RandomizedSearchCV(estimator=dct, param_distributions=param_dist, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_search_dct_y_G3.fit(X_train_y_G3,y_train_y_G3)
print(grid_search_dct_y_G3.best_estimator_)
y_pred_y_G3= grid_search_rf_y_G3.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3,zero_division='warn'))
print(confusion_matrix(y_test_y_G3,y_pred_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=3, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=5,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
              precision    recall  f1-score   support

           0       0.30      0.50      0.37         6
           1       0.57      0.29      0.38        14
           2       0.29      0.33      0.31        12
           3       0.40      0.75      0.52         8
           4       0.92      0.61      0.73        18

    accuracy                           0.48        58
   macro avg       0.49      0.50      0.46        58
weighted avg       0.57      0.48      0.49        58

[[ 3  4  2  1  0]
 [ 1  4  2  0  0]
 [ 2  5  4  0  3]
 [ 0  1  4  6  4]
 [ 0  0  0

### Gaussian Naive Bayesian

In [71]:
clf = GaussianNB()

In [72]:
clf.fit(X_train_x_G1,y_train_x_G1)
y_pred_x_G1= clf.predict(X_test_x_G1)
print(classification_report(y_pred_x_G1,y_test_x_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G1,y_test_x_G1)))
probagnbG1x = clf.predict_proba(X_test_x_G1)

              precision    recall  f1-score   support

           0       0.09      0.17      0.12         6
           1       0.00      0.00      0.00         1
           2       0.67      0.24      0.36        33
           3       0.27      0.60      0.37         5
           4       0.62      0.62      0.62         8

    accuracy                           0.32        53
   macro avg       0.33      0.33      0.29        53
weighted avg       0.55      0.32      0.36        53

Kappa Score: 0.13937753721244928


In [73]:
clf.fit(X_train_x_G3,y_train_x_G3)
y_pred_x_G3= clf.predict(X_test_x_G3)
print(classification_report(y_pred_x_G3,y_test_x_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_x_G3,y_test_x_G3)))
probagnbG3x = clf.predict_proba(X_test_x_G3)

              precision    recall  f1-score   support

           0       1.00      0.27      0.42        41
           1       0.00      0.00      0.00         2
           2       0.08      1.00      0.15         1
           3       0.00      0.00      0.00         2
           4       0.12      0.14      0.13         7

    accuracy                           0.25        53
   macro avg       0.24      0.28      0.14        53
weighted avg       0.79      0.25      0.35        53

Kappa Score: 0.056099732858414963


In [74]:
clf.fit(X_train_y_G1,y_train_y_G1)
y_pred_y_G1 = clf.predict(X_test_y_G1)
print(classification_report(y_pred_y_G1,y_test_y_G1))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G1,y_test_y_G1)))
probagnbG1y = clf.predict_proba(X_test_y_G1)

              precision    recall  f1-score   support

           0       0.11      0.20      0.14         5
           1       1.00      0.42      0.59        26
           2       0.00      0.00      0.00         7
           3       0.12      0.33      0.18         3
           4       0.36      1.00      0.53         4

    accuracy                           0.38        45
   macro avg       0.32      0.39      0.29        45
weighted avg       0.63      0.38      0.42        45

Kappa Score: 0.20454545454545459


In [75]:
clf.fit(X_train_y_G3,y_train_y_G3)
y_pred_y_G3 = clf.predict(X_test_y_G3)
print(classification_report(y_pred_y_G3,y_test_y_G3))
print("Kappa Score: " +str(cohen_kappa_score(y_pred_y_G3,y_test_y_G3)))
probagnbG3y = clf.predict_proba(X_test_y_G3)

              precision    recall  f1-score   support

           0       0.20      0.11      0.14        18
           1       0.71      0.21      0.32        24
           2       0.07      0.10      0.08        10
           3       0.00      0.00      0.00         0
           4       0.33      0.67      0.44         6

    accuracy                           0.21        58
   macro avg       0.26      0.22      0.20        58
weighted avg       0.40      0.21      0.24        58

Kappa Score: 0.048502139800285504


/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
